const fs = require('fs');
let code = fs.readFileSync('frontend/src/pages/Audits.jsx', 'utf8');

const targetContent =               <div className="pt-4 flex gap-3">\n                <button type="button" onClick={() => setShowAddModal(false)} className="flex-1 px-4 py-3 border border-gray-700 rounded-xl text-gray-400 font-bold hover:text-blue-200 transition-colors">Cancel</button>\n                <button type="submit" disabled={savingAudit} className="flex-1 bg-emerald-600 hover:bg-emerald-500 text-blue-200 rounded-xl font-bold transition-colors disabled:opacity-50 flex items-center justify-center gap-2">\n                  {savingAudit ? 'Saving...' : 'Save Audit'}\n                </button>\n              </div>\n            </form>\n          </div>\n        </div>\n      )}\n    </div>\n  );\n};

const replacementContent =               <div className="pt-4 flex gap-3">\n                <button type="button" onClick={() => setShowAddModal(false)} className="flex-1 px-4 py-3 border border-gray-700 rounded-xl text-gray-400 font-bold hover:text-blue-200 transition-colors">Cancel</button>\n                <button type="submit" disabled={savingAudit} className="flex-1 bg-emerald-600 hover:bg-emerald-500 text-blue-200 rounded-xl font-bold transition-colors disabled:opacity-50 flex items-center justify-center gap-2">\n                  {savingAudit ? 'Saving...' : 'Save Audit'}\n                </button>\n              </div>\n            </form>\n          </div>\n        </div>\n      )}\n\n      {showBulkModal && (\n        <div className="fixed inset-0 bg-black/90 flex items-center justify-center z-50 p-4">\n          <div className="bg-brand-card border border-gray-800 rounded-2xl w-full max-w-2xl p-6 relative">\n            <div className="flex items-center justify-between mb-6">\n              <h2 className="text-xl font-bold text-blue-200 flex items-center gap-2">\n                <LayoutDashboard className="w-6 h-6 text-blue-400" /> Bulk Upload Audits\n              </h2>\n              <button onClick={() => setShowBulkModal(false)} className="text-gray-400 hover:text-blue-200"><X className="w-6 h-6" /></button>\n            </div>\n            \n            <form onSubmit={handleBulkSubmit} className="space-y-4">\n              <div className="mb-4">\n                <label className="block text-sm text-gray-400 mb-2">Paste text here (separate each audit with an empty line)</label>\n                <textarea \n                  value={bulkText}\n                  onChange={(e) => setBulkText(e.target.value)}\n                  className="w-full bg-[#1a1a1a] border border-gray-700 rounded-xl p-4 text-blue-200 outline-none h-64 font-mono text-sm"\n                  placeholder="Department : Laundry\\nEmployee No: 1234\\nEmployee Name: John Doe\\nAudit type: Stayover\\nDate: 06/07/2026\\nScore: 90\\nRoom / Area: 101\\n\\nDepartment : ..."\n                />\n              </div>\n              <div className="pt-4 flex gap-3">\n                <button type="button" onClick={() => setShowBulkModal(false)} className="flex-1 px-4 py-3 border border-gray-700 rounded-xl text-gray-400 font-bold hover:text-blue-200 transition-colors">Cancel</button>\n                <button type="submit" disabled={savingBulk} className="flex-1 bg-blue-600 hover:bg-blue-500 text-blue-100 rounded-xl font-bold transition-colors disabled:opacity-50 flex items-center justify-center gap-2">\n                  {savingBulk ? 'Uploading...' : 'Upload Audits'}\n                </button>\n              </div>\n            </form>\n          </div>\n        </div>\n      )}\n    </div>\n  );\n};

code = code.replace(targetContent, replacementContent);
fs.writeFileSync('frontend/src/pages/Audits.jsx', code, 'utf8');
console.log('Fixed Audits.jsx modal rendering');
